name: "Auto Label Issues"
on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Apply labels
        uses: github/issue-labeler@v3.4
        with:
          configuration-path: .github/labeler.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Apply labels for issue titles only
        uses: github/issue-labeler@v3.4
        with:
          configuration-path: .github/labeler-titles.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          include-title: 1
          include-body: 0




          
